language: go

go:
  - 1.14.x

install: true

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: make build

    - stage: "Tests"
      name: "Unit Tests"
      script: go test ./pkg/... -coverprofile=coverage.txt -covermode=count
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: "Code Quality"
      name: "Code Quality Analysis"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.28.3
      script: golangci-lint run

    - stage: "Integration Tests"
      name: "Integration Tests"
      env:
        DOCKER_COMPOSE_VERSION: 1.23.2
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      script: docker-compose -f ./docker-compose-tests.yaml up --abort-on-container-exit --exit-code-from integration-tests && docker-compose -f ./docker-compose-tests.yaml down