language: go

go:
  - 1.14.x

install: true

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: make build

    - stage: "Tests"
      name: "Unit Tests"
      script: go test ./pkg/... -coverprofile=coverage.txt -covermode=count
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: "Code Quality"
      name: "Code Quality Analysis"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.28.3
      script: golangci-lint run